const info_elements = [
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Hydrogen_discharge_tube.jpg/450px-Hydrogen_discharge_tube.jpg",
	  arrangement:"https://www.thoughtco.com/thmb/jWKDzcJiEd5y7qa7b_Ihz9baq2s=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/hydrogenatom-58b6029c3df78cdcd83d98bb.jpg",
	  name: "Hydrogen",
	  atomicMass: "1.00794(4)",
	  electronicConfiguration: "1s1",
	  electronegativity: 2.2,
	  atomicRadius: 37,
	  oxidationStates: "-1 1",
	  standardState: "gas",
	  meltingPoint: 14,
	  boilingPoint: 20,
	  density: 0.0000899,
	  groupBlock: "nonmetal",
	  yearDiscovered: 1766,
	  block: "s",
	  applications: "ammonia production",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Helium_discharge_tube.jpg/330px-Helium_discharge_tube.jpg",
	  name: "Helium",
	  arrangement:"https://www.thoughtco.com/thmb/K7hyFEP6HdbrjmpJh4tujgJjuz8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/heliumatom-58b602983df78cdcd83d95c8.jpg",
	  atomicMass: "4.002602(2)",
	  electronicConfiguration: "1s2",
	  electronegativity: "unknown",
	  atomicRadius: 32,
	  oxidationStates: "unknown",
	  standardState: "gas",
	  meltingPoint: 0.95,
	  boilingPoint: 4,
	  density: 0.0001785,
	  groupBlock: "noble gas",
	  yearDiscovered: 1868,
	  block: "p",
	  applications: "MRI machines",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Lithium_paraffin.jpg/330px-Lithium_paraffin.jpg",
	  name: "Lithium",
	  arrangement:"https://www.thoughtco.com/thmb/rPktFn1EKy3Q2LcE2ATknAweD1g=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/lithiumatom-58b602933df78cdcd83d927b.jpg",
	  atomicMass: "6.941(2)",
	  electronicConfiguration: "[He] 2s1",
	  electronegativity: 0.98,
	  atomicRadius: 134,
	  oxidationStates: 1,
	  standardState: "solid",
	  meltingPoint: 454,
	  boilingPoint: 1615,
	  density: 0.535,
	  groupBlock: "alkali metal",
	  yearDiscovered: 1817,
	  block: "s",
	  applications: "batteries",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Be-140g.jpg/210px-Be-140g.jpg",
	  name: "Beryllium",
	  arrangement:"https://www.thoughtco.com/thmb/OoBeroMYBieiS5ecrmkNPxorKgg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/berylliumatom-58b6028f3df78cdcd83d8f11.jpg",
	  atomicMass: "9.012182(3)",
	  electronicConfiguration: "[He] 2s2",
	  electronegativity: 1.57,
	  atomicRadius: 90,
	  oxidationStates: 2,
	  standardState: "solid",
	  meltingPoint: 1560,
	  boilingPoint: 2743,
	  density: 1.848,
	  groupBlock: "alkaline earth metal",
	  yearDiscovered: 1798,
	  block: "s",
	  applications: "aerospace components",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Boron_R105.jpg/330px-Boron_R105.jpg",
	  name: "Boron",
	  arrangement:"https://www.thoughtco.com/thmb/EcP_kUY5bqs2sDbgnVxjxa_B4rE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/boronatom-58b6028a5f9b5860464c90ab.jpg",
	  atomicMass: "10.811(7)",
	  electronicConfiguration: "[He] 2s2 2p1",
	  electronegativity: 2.04,
	  atomicRadius: 82,
	  oxidationStates: "1 2 3",
	  standardState: "solid",
	  meltingPoint: 2348,
	  boilingPoint: 4273,
	  density: 2.46,
	  groupBlock: "metalloid",
	  yearDiscovered: 1807,
	  block: "p",
	  applications: "fiberglass",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Graphite-and-diamond-with-scale.jpg/330px-Graphite-and-diamond-with-scale.jpg",
	  name: "Carbon",
	  arrangement:"https://www.thoughtco.com/thmb/bE_wb6vjJ_MCUDOYNR36MnWPNCI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/carbonatom-58b602855f9b5860464c8bf6.jpg",
	  atomicMass: "12.0107(8)",
	  electronicConfiguration: "[He] 2s2 2p2",
	  electronegativity: 2.55,
	  atomicRadius: 77,
	  oxidationStates: "-4 -3 -2 -1 1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 3823,
	  boilingPoint: 4300,
	  density: 2.26,
	  groupBlock: "nonmetal",
	  yearDiscovered: "-3750",
	  block: "p",
	  applications: "steelmaking ",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Fluessiger_Stickstoff.jpg/330px-Fluessiger_Stickstoff.jpg",
	  name: "Nitrogen",
	  arrangement:"https://www.thoughtco.com/thmb/-sGUtDTMfUiZPgACj61coujqo7Q=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/nitrogenaton-58b602813df78cdcd83d8348.jpg",
	  atomicMass: "14.0067(2)",
	  electronicConfiguration: "[He] 2s2 2p3",
	  electronegativity: 3.04,
	  atomicRadius: 75,
	  oxidationStates: "-3 -2 -1 1 2 3 4 5",
	  standardState: "gas",
	  meltingPoint: 63,
	  boilingPoint: 77,
	  density: 0.001251,
	  groupBlock: "nonmetal",
	  yearDiscovered: 1772,
	  block: "p",
	  applications: "fertilizer production",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Liquid_oxygen_in_a_beaker_4.jpg/375px-Liquid_oxygen_in_a_beaker_4.jpg",
	  name: "Oxygen",
	  arrangement:"https://www.thoughtco.com/thmb/wAHdnSy9-FZqavnxWPu98roXQEs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/oxygen-58b6027d3df78cdcd83d7f42.jpg",
	  atomicMass: "15.9994(3)",
	  electronicConfiguration: "[He] 2s2 2p4",
	  electronegativity: 3.44,
	  atomicRadius: 73,
	  oxidationStates: "-2 -1 1 2",
	  standardState: "gas",
	  meltingPoint: 55,
	  boilingPoint: 90,
	  density: 0.001429,
	  groupBlock: "nonmetal",
	  yearDiscovered: 1774,
	  block: "p",
	  applications: "medical applications",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Fluoro_liquido_a_-196%C2%B0C_1.jpg/330px-Fluoro_liquido_a_-196%C2%B0C_1.jpg",
	  name: "Fluorine",
	  arrangement:"https://www.thoughtco.com/thmb/7JSiwEAMZeYqbZJyvc_0F1dKmeU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/fluorineatom-58b602793df78cdcd83d7b50.jpg",
	  atomicMass: "18.9984032(5)",
	  electronicConfiguration: "[He] 2s2 2p5",
	  electronegativity: 3.98,
	  atomicRadius: 71,
	  oxidationStates: -1,
	  standardState: "gas",
	  meltingPoint: 54,
	  boilingPoint: 85,
	  density: 0.001696,
	  groupBlock: "halogen",
	  yearDiscovered: 1886,
	  block: "p",
	  applications: "toothpaste",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Neon_discharge_tube.jpg/330px-Neon_discharge_tube.jpg",
	  name: "Neon",
	  arrangement:"https://www.thoughtco.com/thmb/AU2vL5mVCKVvPLIqIGniKScaTB0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/neonatom-58b602755f9b5860464c7e5a.jpg",
	  atomicMass: "20.1797(6)",
	  electronicConfiguration: "[He] 2s2 2p6",
	  electronegativity: "unknown",
	  atomicRadius: 69,
	  oxidationStates: "unknown",
	  standardState: "gas",
	  meltingPoint: 25,
	  boilingPoint: 27,
	  density: 0.0009,
	  groupBlock: "noble gas",
	  yearDiscovered: 1898,
	  block: "p",
	  applications: "laser technology",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Na_%28Sodium%29.jpg/330px-Na_%28Sodium%29.jpg",
	  name: "Sodium",
	  arrangement:"https://www.thoughtco.com/thmb/Sl31Gi_9kAmJX98M8H1q3lI-geA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/sodiumatom-58b602715f9b5860464c7a22.jpg",
	  atomicMass: "22.98976928(2)",
	  electronicConfiguration: "[Ne] 3s1",
	  electronegativity: 0.93,
	  atomicRadius: 154,
	  oxidationStates: "-1 1",
	  standardState: "solid",
	  meltingPoint: 371,
	  boilingPoint: 1156,
	  density: 0.968,
	  groupBlock: "alkali metal",
	  yearDiscovered: 1807,
	  block: "s",
	  applications: "soap making",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/CSIRO_ScienceImage_2893_Crystalised_magnesium.jpg/330px-CSIRO_ScienceImage_2893_Crystalised_magnesium.jpg",
	  name: "Magnesium",
	  arrangement:"https://www.thoughtco.com/thmb/CFRjPrUSjcoQeAyOe9u3v-4t1J8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/magnesiumatom-58b6026b5f9b5860464c7467.jpg",
	  atomicMass: "24.3050(6)",
	  electronicConfiguration: "[Ne] 3s2",
	  electronegativity: 1.31,
	  atomicRadius: 130,
	  oxidationStates: "1 2",
	  standardState: "solid",
	  meltingPoint: 923,
	  boilingPoint: 1363,
	  density: 1.738,
	  groupBlock: "alkaline earth metal",
	  yearDiscovered: 1808,
	  block: "s",
	  applications: "fireworks",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Aluminium-4.jpg/330px-Aluminium-4.jpg",
	  name: "Aluminium",
	  arrangement:"https://www.thoughtco.com/thmb/MsX9Xff8Hmk6opviudMJ3jJE8oQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/aluminiumatom-58b602655f9b5860464c6f7d.jpg",
	  atomicMass: "26.9815386(8)",
	  electronicConfiguration: "[Ne] 3s2 3p1",
	  electronegativity: 1.61,
	  atomicRadius: 118,
	  oxidationStates: "1 3",
	  standardState: "solid",
	  meltingPoint: 933,
	  boilingPoint: 2792,
	  density: 2.7,
	  groupBlock: "metal",
	  yearDiscovered: "Ancient",
	  block: "p",
	  applications: "aircraft manufacturing",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/SiliconCroda.jpg/330px-SiliconCroda.jpg",
	  name: "Silicon",
	  arrangement:"https://www.thoughtco.com/thmb/kZfE7-Gqm39-UQ-A5Gpt901eUd8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/siliconatom-58b602613df78cdcd83d63e3.jpg",
	  atomicMass: "28.0855(3)",
	  electronicConfiguration: "[Ne] 3s2 3p2",
	  electronegativity: 1.9,
	  atomicRadius: 111,
	  oxidationStates: "-4 -3 -2 -1 1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 1687,
	  boilingPoint: 3173,
	  density: 2.33,
	  groupBlock: "metalloid",
	  yearDiscovered: 1854,
	  block: "p",
	  applications: "semiconductors",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Phosphor-rot-violett.jpg/357px-Phosphor-rot-violett.jpg",
	  name: "Phosphorus",
	  arrangement:"https://www.thoughtco.com/thmb/rw4EPZyltI_8XYFTCFuJ7-YXvjk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/phosphorusatom-58b6025c5f9b5860464c65dc.jpg",
	  atomicMass: "30.973762(2)",
	  electronicConfiguration: "[Ne] 3s2 3p3",
	  electronegativity: 2.19,
	  atomicRadius: 106,
	  oxidationStates: "-3 -2 -1 1 2 3 4 5",
	  standardState: "solid",
	  meltingPoint: 317,
	  boilingPoint: 554,
	  density: 1.823,
	  groupBlock: "nonmetal",
	  yearDiscovered: 1669,
	  block: "p",
	  applications: "fertilizers",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sulfur_-_El_Desierto_mine%2C_San_Pablo_de_Napa%2C_Daniel_Campos_Province%2C_Potos%C3%AD%2C_Bolivia.jpg/330px-Sulfur_-_El_Desierto_mine%2C_San_Pablo_de_Napa%2C_Daniel_Campos_Province%2C_Potos%C3%AD%2C_Bolivia.jpg",
	  name: "Sulphur",
	  arrangement:"https://www.thoughtco.com/thmb/JUu9k31Fj5NF1siJyNeBPFxCDi8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/sulfuratom-58b602563df78cdcd83d5a9d.jpg",
	  atomicMass: "32.065(5)",
	  electronicConfiguration: "[Ne] 3s2 3p4",
	  electronegativity: 2.58,
	  atomicRadius: 102,
	  oxidationStates: "-2 -1 1 2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 388,
	  boilingPoint: 718,
	  density: 1.96,
	  groupBlock: "nonmetal",
	  yearDiscovered: "-2000",
	  block: "p",
	  applications: "rubber vulcanization",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Chlorine_in_bottle.jpg/330px-Chlorine_in_bottle.jpg",
	  name: "Chlorine",
	  arrangement:"https://www.thoughtco.com/thmb/Q0d-ly9yZSiwsyOFW9y3IdZBZMw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/chlorineatom-58b602515f9b5860464c5c02.jpg",
	  atomicMass: "35.453(2)",
	  electronicConfiguration: "[Ne] 3s2 3p5",
	  electronegativity: 3.16,
	  atomicRadius: 99,
	  oxidationStates: "-1 1 2 3 4 5 6 7",
	  standardState: "gas",
	  meltingPoint: 172,
	  boilingPoint: 239,
	  density: 0.003214,
	  groupBlock: "halogen",
	  yearDiscovered: 1774,
	  block: "p",
	  applications: "PVC production",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Argon_discharge_tube.jpg/330px-Argon_discharge_tube.jpg",
	  name: "Argon",
	  arrangement:"https://www.thoughtco.com/thmb/vcYSQ8xASBn7Qqh6DUZLJhRQBIA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/argonatom-58b44b6f5f9b586046e5840d.jpg",
	  atomicMass: "39.948(1)",
	  electronicConfiguration: "[Ne] 3s2 3p6",
	  electronegativity: "unknown",
	  atomicRadius: 97,
	  oxidationStates: "unknown",
	  standardState: "gas",
	  meltingPoint: 84,
	  boilingPoint: 87,
	  density: 0.001784,
	  groupBlock: "noble gas",
	  yearDiscovered: 1894,
	  block: "p",
	  applications: "welding/lighting",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Potassium-2.jpg/330px-Potassium-2.jpg",
	  name: "Potassium",
	  arrangement:"https://www.thoughtco.com/thmb/9ANbbk7eARyyfTiY8C1O39SlKHQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/potassiumatom-58b602485f9b5860464c55ea.jpg",
	  atomicMass: "39.0983(1)",
	  electronicConfiguration: "[Ar] 4s1",
	  electronegativity: 0.82,
	  atomicRadius: 196,
	  oxidationStates: 1,
	  standardState: "solid",
	  meltingPoint: 337,
	  boilingPoint: 1032,
	  density: 0.856,
	  groupBlock: "alkali metal",
	  yearDiscovered: 1807,
	  block: "s",
	  applications: "food preservation",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Calcium_unter_Argon_Schutzgasatmosph%C3%A4re.jpg/330px-Calcium_unter_Argon_Schutzgasatmosph%C3%A4re.jpg",
	  name: "Calcium",
	  arrangement:"https://www.thoughtco.com/thmb/QtBHXgYSlie6kegV5ZCsHKgVHrs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Calcium-58b602433df78cdcd83d4c16.jpg",
	  atomicMass: "40.078(4)",
	  electronicConfiguration: "[Ar] 4s2",
	  electronegativity: 1,
	  atomicRadius: 174,
	  oxidationStates: 2,
	  standardState: "solid",
	  meltingPoint: 1115,
	  boilingPoint: 1757,
	  density: 1.55,
	  groupBlock: "alkaline earth metal",
	  yearDiscovered: "Ancient",
	  block: "s",
	  applications: "dietary supplements",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Scandium_sublimed_dendritic_and_1cm3_cube.jpg/330px-Scandium_sublimed_dendritic_and_1cm3_cube.jpg",
	  name: "Scandium",
	  arrangement:"https://www.thoughtco.com/thmb/qVyjw7tPgcrvwvSe1e33it2ZVAU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Scandium-58b6023e3df78cdcd83d49e1.jpg",
	  atomicMass: "44.955912(6)",
	  electronicConfiguration: "[Ar] 3d1 4s2",
	  electronegativity: 1.36,
	  atomicRadius: 144,
	  oxidationStates: "1 2 3",
	  standardState: "solid",
	  meltingPoint: 1814,
	  boilingPoint: 3103,
	  density: 2.985,
	  groupBlock: "transition metal",
	  yearDiscovered: 1876,
	  block: "d",
	  applications: "aerospace components",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Titan-crystal_bar.JPG/330px-Titan-crystal_bar.JPG",
	  name: "Titanium",
	  arrangement:"https://www.thoughtco.com/thmb/Wtngomrhh_0hnBLeByj0Qi55P_w=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Titanium-58b602395f9b5860464c4d8e.jpg",
	  atomicMass: "47.867(1)",
	  electronicConfiguration: "[Ar] 3d2 4s2",
	  electronegativity: 1.54,
	  atomicRadius: 136,
	  oxidationStates: "-1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 1941,
	  boilingPoint: 3560,
	  density: 4.507,
	  groupBlock: "transition metal",
	  yearDiscovered: 1791,
	  block: "d",
	  applications: "aerospace components",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Vanadium_crystal_bar_and_1cm3_cube.jpg/330px-Vanadium_crystal_bar_and_1cm3_cube.jpg",
	  name: "Vanadium",
	  arrangement:"https://www.thoughtco.com/thmb/gkB4841v8_Ppz_SMvGt-qA5qoy4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Vanadium-58b602345f9b5860464c4ae3.jpg",
	  atomicMass: "50.9415(1)",
	  electronicConfiguration: "[Ar] 3d3 4s2",
	  electronegativity: 1.63,
	  atomicRadius: 125,
	  oxidationStates: "-1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 2183,
	  boilingPoint: 3680,
	  density: 6.11,
	  groupBlock: "transition metal",
	  yearDiscovered: 1803,
	  block: "d",
	  applications: "rechargeable batteries",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Chromium_crystals_and_1cm3_cube.jpg/330px-Chromium_crystals_and_1cm3_cube.jpg",
	  name: "Chromium",
	  arrangement:"https://www.thoughtco.com/thmb/-kwkVY05xuWoe2CUo3gY7S3-GsM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Chromium-58b5c2313df78cdcd8b9d235.jpg",
	  atomicMass: "51.9961(6)",
	  electronicConfiguration: "[Ar] 3d5 4s1",
	  electronegativity: 1.66,
	  atomicRadius: 127,
	  oxidationStates: "-2 -1 1 2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 2180,
	  boilingPoint: 2944,
	  density: 7.14,
	  groupBlock: "transition metal",
	  yearDiscovered: "Ancient",
	  block: "d",
	  applications: "leather tanning",
	},
  
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Manganese_electrolytic_and_1cm3_cube.jpg/330px-Manganese_electrolytic_and_1cm3_cube.jpg",
	  name: "Manganese",
	  arrangement:"https://www.thoughtco.com/thmb/lStpNT00j9wM-YEDMn9bvIqhtMQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Manganese-58b602295f9b5860464c4532.jpg",
	  atomicMass: "54.938045(5)",
	  electronicConfiguration: "[Ar] 3d5 4s2",
	  electronegativity: 1.55,
	  atomicRadius: 139,
	  oxidationStates: "-3 -2 -1 1 2 3 4 5 6 7",
	  standardState: "solid",
	  meltingPoint: 1519,
	  boilingPoint: 2334,
	  density: 7.47,
	  groupBlock: "transition metal",
	  yearDiscovered: 1774,
	  block: "d",
	  applications: "steelmaking",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Iron_electrolytic_and_1cm3_cube.jpg/330px-Iron_electrolytic_and_1cm3_cube.jpg",
	  name: "Iron",
	  arrangement:"https://www.thoughtco.com/thmb/mIPLT3KKf0shL7vW4cCi6TRx_tw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Iron-58b602243df78cdcd83d3d5a.jpg",
	  atomicMass: "55.845(2)",
	  electronicConfiguration: "[Ar] 3d6 4s2",
	  electronegativity: 1.83,
	  atomicRadius: 125,
	  oxidationStates: "-2 -1 1 2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 1811,
	  boilingPoint: 3134,
	  density: 7.874,
	  groupBlock: "transition metal",
	  yearDiscovered: "-5000",
	  block: "d",
	  applications: "machinery field",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Kobalt_electrolytic_and_1cm3_cube.jpg/330px-Kobalt_electrolytic_and_1cm3_cube.jpg",
	  name: "Cobalt",
	  arrangement:"https://www.thoughtco.com/thmb/knV-dg-96lI5VdunCugF6piaYIU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Cobalt-58b6021e5f9b5860464c40d8.jpg",
	  atomicMass: "58.933195(5)",
	  electronicConfiguration: "[Ar] 3d7 4s2",
	  electronegativity: 1.88,
	  atomicRadius: 126,
	  oxidationStates: "-1 1 2 3 4 5",
	  standardState: "solid",
	  meltingPoint: 1768,
	  boilingPoint: 3200,
	  density: 8.9,
	  groupBlock: "transition metal",
	  yearDiscovered: "1735",
	  block: "d",
	  applications: "magnetic materials",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nickel_electrolytic_and_1cm3_cube.jpg/330px-Nickel_electrolytic_and_1cm3_cube.jpg",
	  name: "Nickel",
	  arrangement:"https://www.thoughtco.com/thmb/aqKR-Ig2Ekzb2VCVVTA8wP7a4qM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Nickel-58b602195f9b5860464c3e1d.jpg",
	  atomicMass: "58.6934(4)",
	  electronicConfiguration: "[Ar] 3d8 4s2",
	  electronegativity: 1.91,
	  atomicRadius: 121,
	  oxidationStates: "-1 1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 1728,
	  boilingPoint: 3186,
	  density: 8.908,
	  groupBlock: "transition metal",
	  yearDiscovered: 1751,
	  block: "d",
	  applications: "producing coins",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/NatCopper.jpg/330px-NatCopper.jpg",
	  name: "Copper",
	  arrangement:"https://www.thoughtco.com/thmb/tXsbZE_uXzS3IESw2fRC-Yj_jDE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Copper-58b602153df78cdcd83d352e.jpg",
	  atomicMass: "63.546(3)",
	  electronicConfiguration: "[Ar] 3d10 4s1",
	  electronegativity: 1.9,
	  atomicRadius: 138,
	  oxidationStates: "1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 1358,
	  boilingPoint: 3200,
	  density: 8.92,
	  groupBlock: "transition metal",
	  yearDiscovered: "-9000",
	  block: "d",
	  applications: "electrical wiring",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Zinc_fragment_sublimed_and_1cm3_cube.jpg/330px-Zinc_fragment_sublimed_and_1cm3_cube.jpg",
	  name: "Zinc",
	  arrangement:"https://www.thoughtco.com/thmb/_HIvPSxlHNK6LanBwUfHwjqadE0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Zinc-58b6020f3df78cdcd83d332a.jpg",
	  atomicMass: "65.38(2)",
	  electronicConfiguration: "[Ar] 3d10 4s2",
	  electronegativity: 1.65,
	  atomicRadius: 131,
	  oxidationStates: 2,
	  standardState: "solid",
	  meltingPoint: 693,
	  boilingPoint: 1180,
	  density: 7.14,
	  groupBlock: "transition metal",
	  yearDiscovered: 1746,
	  block: "d",
	  applications: "galvanizing steel",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Gallium_crystals.jpg/330px-Gallium_crystals.jpg",
	  name: "Gallium",
	  arrangement:"https://www.thoughtco.com/thmb/doLwiJsTrguwqLB-RQXbu7KeffA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Gallium-58b6020b5f9b5860464c36a7.jpg",
	  atomicMass: "69.723(1)",
	  electronicConfiguration: "[Ar] 3d10 4s2 4p1",
	  electronegativity: 1.81,
	  atomicRadius: 126,
	  oxidationStates: "1 2 3",
	  standardState: "solid",
	  meltingPoint: 303,
	  boilingPoint: 2477,
	  density: 5.904,
	  groupBlock: "metal",
	  yearDiscovered: 1875,
	  block: "p",
	  applications: "solar cells",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Polycrystalline-germanium.jpg/330px-Polycrystalline-germanium.jpg",
	  name: "Germanium",
	  arrangement:"https://www.thoughtco.com/thmb/Zm_W9bDLn25lPvm2itC50kK97NM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Germanium-58b602065f9b5860464c3353.jpg",
	  atomicMass: "72.64(1)",
	  electronicConfiguration: "[Ar] 3d10 4s2 4p2",
	  electronegativity: 2.01,
	  atomicRadius: 122,
	  oxidationStates: "-4 1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 1211,
	  boilingPoint: 3093,
	  density: 5.323,
	  groupBlock: "metalloid",
	  yearDiscovered: 1886,
	  block: "p",
	  applications: "infrared optics",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Arsen_1a.jpg/330px-Arsen_1a.jpg",
	  name: "Arsenic",
	  arrangement:"https://www.thoughtco.com/thmb/gB2g6875-64pvS4_35Janc7gsn0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Arsenic-58b602013df78cdcd83d2cac.jpg",
	  atomicMass: "74.92160(2)",
	  electronicConfiguration: "[Ar] 3d10 4s2 4p3",
	  electronegativity: 2.18,
	  atomicRadius: 119,
	  oxidationStates: "-3 2 3 5",
	  standardState: "solid",
	  meltingPoint: 1090,
	  boilingPoint: 887,
	  density: 5.727,
	  groupBlock: "metalloid",
	  yearDiscovered: "815",
	  block: "p",
	  applications: "wood preservative",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/SeBlackRed.jpg/330px-SeBlackRed.jpg",
	  name: "Selenium",
	  arrangement:"https://www.thoughtco.com/thmb/qctO0_GoA8CbI847X_eMP_kh_DM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Selenium-58b601fd3df78cdcd83d2a90.jpg",
	  atomicMass: "78.96(3)",
	  electronicConfiguration: "[Ar] 3d10 4s2 4p4",
	  electronegativity: 2.55,
	  atomicRadius: 116,
	  oxidationStates: "-2 2 4 6",
	  standardState: "solid",
	  meltingPoint: 494,
	  boilingPoint: 958,
	  density: 4.819,
	  groupBlock: "nonmetal",
	  yearDiscovered: 1817,
	  block: "p",
	  applications: "photovoltaic cell",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Bromine_vial_in_acrylic_cube.jpg/330px-Bromine_vial_in_acrylic_cube.jpg",
	  name: "Bromine",
	  arrangement:"https://www.thoughtco.com/thmb/TRxgE5McL0k3Z05hlg8Xx7FDgwM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Bromine-58b601f93df78cdcd83d2817.jpg",
	  atomicMass: "79.904(1)",
	  electronicConfiguration: "[Ar] 3d10 4s2 4p5",
	  electronegativity: 2.96,
	  atomicRadius: 114,
	  oxidationStates: "-1 1 3 4 5 7",
	  standardState: "liquid",
	  meltingPoint: 266,
	  boilingPoint: 332,
	  density: 3.12,
	  groupBlock: "halogen",
	  yearDiscovered: 1826,
	  block: "p",
	  applications: "flame retardant",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Krypton_discharge_tube.jpg/330px-Krypton_discharge_tube.jpg",
	  name: "Krypton",
	  arrangement:"https://www.thoughtco.com/thmb/Gwl8uKwrHoamhHeOITvofMJ4n9g=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Krypton-58b601f43df78cdcd83d25c7.jpg",
	  atomicMass: "83.798(2)",
	  electronicConfiguration: "[Ar] 3d10 4s2 4p6",
	  electronegativity: "unknown",
	  atomicRadius: 110,
	  oxidationStates: 2,
	  standardState: "gas",
	  meltingPoint: 116,
	  boilingPoint: 120,
	  density: 0.00375,
	  groupBlock: "noble gas",
	  yearDiscovered: 1898,
	  block: "p",
	  applications: "laser technology",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Rb5.JPG/330px-Rb5.JPG",
	  name: "Rubidium",
	  arrangement:"https://www.thoughtco.com/thmb/g6yjzjYpZnYyXE3G41RO0ArHVzc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Rubidium-58b601ee3df78cdcd83d20d6.jpg",
	  atomicMass: "85.4678(3)",
	  electronicConfiguration: "[Kr] 5s1",
	  electronegativity: 0.82,
	  atomicRadius: 211,
	  oxidationStates: 1,
	  standardState: "solid",
	  meltingPoint: 312,
	  boilingPoint: 961,
	  density: 1.532,
	  groupBlock: "alkali metal",
	  yearDiscovered: 1861,
	  block: "s",
	  applications: "atomic clock",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Strontium_destilled_crystals.jpg/330px-Strontium_destilled_crystals.jpg",
	  name: "Strontium",
	  arrangement:"https://www.thoughtco.com/thmb/8KPj4fWzZWG8BSVpDxxiDmcbkPk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Strontium-58b5c2035f9b586046c8f2bb.jpg",
	  atomicMass: "87.62(1)",
	  electronicConfiguration: "[Kr] 5s2",
	  electronegativity: 0.95,
	  atomicRadius: 192,
	  oxidationStates: 2,
	  standardState: "solid",
	  meltingPoint: 1050,
	  boilingPoint: 1655,
	  density: 2.63,
	  groupBlock: "alkaline earth metal",
	  yearDiscovered: 1790,
	  block: "s",
	  applications: "pyrotechnic flares",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Yttrium_sublimed_dendritic_and_1cm3_cube.jpg/330px-Yttrium_sublimed_dendritic_and_1cm3_cube.jpg",
	  name: "Yttrium",
	  arrangement:"https://www.thoughtco.com/thmb/Ioju7Oro0o0c2gXhjRIQIwi7fX8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Yttrium-58b601e53df78cdcd83d1af7.jpg",
	  atomicMass: "88.90585(2)",
	  electronicConfiguration: "[Kr] 4d1 5s2",
	  electronegativity: 1.22,
	  atomicRadius: 162,
	  oxidationStates: "1 2 3",
	  standardState: "solid",
	  meltingPoint: 1799,
	  boilingPoint: 3618,
	  density: 4.472,
	  groupBlock: "transition metal",
	  yearDiscovered: 1794,
	  block: "d",
	  applications: "superconductors",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Zirconium_crystal_bar_and_1cm3_cube.jpg/330px-Zirconium_crystal_bar_and_1cm3_cube.jpg",
	  name: "Zirconium",
	  arrangement:"https://www.thoughtco.com/thmb/R324BKfdLmIslcVnKHuo5TzB4B0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Zirconium-58b601e03df78cdcd83d1948.jpg",
	  atomicMass: "91.224(2)",
	  electronicConfiguration: "[Kr] 4d2 5s2",
	  electronegativity: 1.33,
	  atomicRadius: 148,
	  oxidationStates: "1 2 3 4",
	  standardState: "solid",
	  meltingPoint: 2128,
	  boilingPoint: 4682,
	  density: 6.511,
	  groupBlock: "transition metal",
	  yearDiscovered: 1789,
	  block: "d",
	  applications: "nuclear reactor",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Niobium_crystals_and_1cm3_cube.jpg/330px-Niobium_crystals_and_1cm3_cube.jpg",
	  name: "Niobium",
	  arrangement:"https://www.thoughtco.com/thmb/lPmFLar1b9e-GQeJqm3UcrY0BzQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Niobium-58b601dc5f9b5860464c1b39.jpg",
	  atomicMass: "92.90638(2)",
	  electronicConfiguration: "[Kr] 4d4 5s1",
	  electronegativity: 1.6,
	  atomicRadius: 137,
	  oxidationStates: "-1 2 3 4 5",
	  standardState: "solid",
	  meltingPoint: 2750,
	  boilingPoint: 5017,
	  density: 8.57,
	  groupBlock: "transition metal",
	  yearDiscovered: 1801,
	  block: "d",
	  applications: "steel alloy",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Molybdenum_crystaline_fragment_and_1cm3_cube.jpg/330px-Molybdenum_crystaline_fragment_and_1cm3_cube.jpg",
	  name: "Molybdenum",
	  arrangement:"https://www.thoughtco.com/thmb/lmIaV-e_YEuTUQ7vkdWm_MnPX-Y=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Molybdenum-58b601d73df78cdcd83d149f.jpg",
	  atomicMass: "95.96(2)",
	  electronicConfiguration: "[Kr] 4d5 5s1",
	  electronegativity: 2.16,
	  atomicRadius: 145,
	  oxidationStates: "-2 -1 1 2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 2896,
	  boilingPoint: 4912,
	  density: 10.28,
	  groupBlock: "transition metal",
	  yearDiscovered: 1778,
	  block: "d",
	  applications: "catalyst",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Technetium-sample-cropped.jpg/330px-Technetium-sample-cropped.jpg",
	  name: "Technetium",
	  arrangement:"https://www.thoughtco.com/thmb/gQO6GGsydbpPJH9-z4Ghsq2EVcc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Technetium-58b601d33df78cdcd83d1289.jpg",
	  atomicMass: [98],
	  electronicConfiguration: "[Kr] 4d5 5s2",
	  electronegativity: 1.9,
	  atomicRadius: 156,
	  oxidationStates: "-3 -1 1 2 3 4 5 6 7",
	  standardState: "solid",
	  meltingPoint: 2430,
	  boilingPoint: 4538,
	  density: 11.5,
	  groupBlock: "transition metal",
	  yearDiscovered: 1937,
	  block: "d",
	  applications: "medical imaging",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Ruthenium_a_half_bar.jpg/330px-Ruthenium_a_half_bar.jpg",
	  name: "Ruthenium",
	  arrangement:"https://www.thoughtco.com/thmb/TedZUw2X4Su-WfIaLJTywNCDXfA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Ruthenium-58b601ce5f9b5860464c14df.jpg",
	  atomicMass: "101.07(2)",
	  electronicConfiguration: "[Kr] 4d7 5s1",
	  electronegativity: 2.2,
	  atomicRadius: 126,
	  oxidationStates: "-2 1 2 3 4 5 6 7 8",
	  standardState: "solid",
	  meltingPoint: 2607,
	  boilingPoint: 4423,
	  density: 12.37,
	  groupBlock: "transition metal",
	  yearDiscovered: 1827,
	  block: "d",
	  applications: "electricity",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Rhodium_powder_pressed_melted.jpg/330px-Rhodium_powder_pressed_melted.jpg",
	  name: "Rhodium",
	  arrangement:"https://www.thoughtco.com/thmb/sLeKuGgWqGb5_m6V1E27B_IPjqY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Rhodium-58b601ca5f9b5860464c12f6.jpg",
	  atomicMass: "102.90550(2)",
	  electronicConfiguration: "[Kr] 4d8 5s1",
	  electronegativity: 2.28,
	  atomicRadius: 135,
	  oxidationStates: "-1 1 2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 2237,
	  boilingPoint: 3968,
	  density: 12.45,
	  groupBlock: "transition metal",
	  yearDiscovered: 1803,
	  block: "d",
	  applications: "electricity",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Palladium_%2846_Pd%29.jpg/330px-Palladium_%2846_Pd%29.jpg",
	  name: "Palladium",
	  arrangement:"https://www.thoughtco.com/thmb/sZcYrAmSAtboHd1lJm4UvhHjOfQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Palladium-58b601c53df78cdcd83d0a00.jpg",
	  atomicMass: "106.42(1)",
	  electronicConfiguration: "[Kr] 4d10",
	  electronegativity: 2.2,
	  atomicRadius: 131,
	  oxidationStates: "2 4",
	  standardState: "solid",
	  meltingPoint: 1828,
	  boilingPoint: 3236,
	  density: 12.023,
	  groupBlock: "transition metal",
	  yearDiscovered: 1803,
	  block: "d",
	  applications: "catalytic converter",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Silver_crystal.jpg/330px-Silver_crystal.jpg",
	  name: "Silver",
	  arrangement:"https://www.thoughtco.com/thmb/543fo4vHe1H-YMvstytHvBhpRew=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Silver-58b601c15f9b5860464c0e8f.jpg",
	  atomicMass: "107.8682(2)",
	  electronicConfiguration: "[Kr] 4d10 5s1",
	  electronegativity: 1.93,
	  atomicRadius: 153,
	  oxidationStates: "1 2 3",
	  standardState: "solid",
	  meltingPoint: 1235,
	  boilingPoint: 2435,
	  density: 10.49,
	  groupBlock: "transition metal",
	  yearDiscovered: "-5000",
	  block: "d",
	  applications: "photography",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cadmium-crystal_bar.jpg/330px-Cadmium-crystal_bar.jpg",
	  name: "Cadmium",
	  arrangement:"https://www.thoughtco.com/thmb/-fTZyXYbsbTY3mdtWtye1a0W0d4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Cadmium-58b601bd5f9b5860464c0cba.jpg",
	  atomicMass: "112.411(8)",
	  electronicConfiguration: "[Kr] 4d10 5s2",
	  electronegativity: 1.69,
	  atomicRadius: 148,
	  oxidationStates: 2,
	  standardState: "solid",
	  meltingPoint: 594,
	  boilingPoint: 1040,
	  density: 8.65,
	  groupBlock: "transition metal",
	  yearDiscovered: 1817,
	  block: "d",
	  applications: "batteries",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Indium.jpg/330px-Indium.jpg",
	  name: "Indium",
	  arrangement:"https://www.thoughtco.com/thmb/qRVh2ra_qaNZ-rhHF7CFgUa9oic=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Indium-58b5c2155f9b586046c8f341.jpg",
	  atomicMass: "114.818(3)",
	  electronicConfiguration: "[Kr] 4d10 5s2 5p1",
	  electronegativity: 1.78,
	  atomicRadius: 144,
	  oxidationStates: "1 2 3",
	  standardState: "solid",
	  meltingPoint: 430,
	  boilingPoint: 2345,
	  density: 7.31,
	  groupBlock: "metal",
	  yearDiscovered: 1863,
	  block: "p",
	  applications: "LCD screens",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Sn-Alpha-Beta.jpg/330px-Sn-Alpha-Beta.jpg",
	  name: "Tin",
	  arrangement:"https://www.thoughtco.com/thmb/UHqsRlMfzPhFB8m771oBzw3zvA4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Tin-58b601b23df78cdcd83d0197.jpg",
	  atomicMass: "118.710(7)",
	  electronicConfiguration: "[Kr] 4d10 5s2 5p2",
	  electronegativity: 1.96,
	  atomicRadius: 141,
	  oxidationStates: "-4 2 4",
	  standardState: "solid",
	  meltingPoint: 505,
	  boilingPoint: 2875,
	  density: 7.31,
	  groupBlock: "metal",
	  yearDiscovered: "-3500",
	  block: "p",
	  applications: "food packaging",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Antimony-4.jpg/330px-Antimony-4.jpg",
	  name: "Antimony",
	  arrangement:"https://www.thoughtco.com/thmb/ay75GqvtYE0mWMX417vuobtvCAc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Antimony-58b601ae3df78cdcd83cfea4.jpg",
	  atomicMass: "121.760(1)",
	  electronicConfiguration: "[Kr] 4d10 5s2 5p3",
	  electronegativity: 2.05,
	  atomicRadius: 138,
	  oxidationStates: "-3 3 5",
	  standardState: "solid",
	  meltingPoint: 904,
	  boilingPoint: 1860,
	  density: 6.697,
	  groupBlock: "metalloid",
	  yearDiscovered: "815",
	  block: "p",
	  applications: "flame returndant",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Tellurium2.jpg/330px-Tellurium2.jpg",
	  name: "Tellurium",
	  arrangement:"https://www.thoughtco.com/thmb/o6LOfLp_ebbXbN5LjyodC4mS2os=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Tellurium-58b601a93df78cdcd83cfabb.jpg",
	  atomicMass: "127.60(3)",
	  electronicConfiguration: "[Kr] 4d10 5s2 5p4",
	  electronegativity: 2.1,
	  atomicRadius: 135,
	  oxidationStates: "-2 2 4 5 6",
	  standardState: "solid",
	  meltingPoint: 723,
	  boilingPoint: 1261,
	  density: 6.24,
	  groupBlock: "metalloid",
	  yearDiscovered: 1782,
	  block: "p",
	  applications: "thermoelectricdevice",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Sample_of_iodine.jpg/330px-Sample_of_iodine.jpg",
	  name: "Iodine",
	  arrangement:"https://www.thoughtco.com/thmb/OC31WUxTQpbKTes3wfxnWfCw_DQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Iodine-58b601a35f9b5860464bfeb4.jpg",
	  atomicMass: "126.90447(3)",
	  electronicConfiguration: "[Kr] 4d10 5s2 5p5",
	  electronegativity: 2.66,
	  atomicRadius: 133,
	  oxidationStates: "-1 1 3 5 7",
	  standardState: "solid",
	  meltingPoint: 387,
	  boilingPoint: 457,
	  density: 4.94,
	  groupBlock: "halogen",
	  yearDiscovered: 1811,
	  block: "p",
	  applications: "pharmas",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Xenon_discharge_tube.jpg/330px-Xenon_discharge_tube.jpg",
	  name: "Xenon",
	  arrangement:"https://www.thoughtco.com/thmb/DtXzLsEWU4f2yyavk8DNNJH2Ulk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Xenon-58b6019e3df78cdcd83cf4ad.jpg",
	  atomicMass: "131.293(6)",
	  electronicConfiguration: "[Kr] 4d10 5s2 5p6",
	  electronegativity: "unknown",
	  atomicRadius: 130,
	  oxidationStates: "2 4 6 8",
	  standardState: "gas",
	  meltingPoint: 161,
	  boilingPoint: 165,
	  density: 0.0059,
	  groupBlock: "noble gas",
	  yearDiscovered: 1898,
	  block: "p",
	  applications: "anesthesia",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Cesium.jpg/330px-Cesium.jpg",
	  name: "Caesium",
	  arrangement:"https://www.thoughtco.com/thmb/8p5ncQoOehZQc5zgtKSFm6GBBYM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Caesium-58b601983df78cdcd83cf1fa.jpg",
	  atomicMass: "132.9054519(2)",
	  electronicConfiguration: "[Xe] 6s1",
	  electronegativity: 0.79,
	  atomicRadius: 225,
	  oxidationStates: 1,
	  standardState: "solid",
	  meltingPoint: 302,
	  boilingPoint: 944,
	  density: 1.879,
	  groupBlock: "alkali metal",
	  yearDiscovered: 1860,
	  block: "s",
	  applications: "drilling fluid",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Barium_unter_Argon_Schutzgas_Atmosph%C3%A4re.jpg/330px-Barium_unter_Argon_Schutzgas_Atmosph%C3%A4re.jpg",
	  name: "Barium",
	  arrangement:"https://www.thoughtco.com/thmb/m05AmqyGcrzfzGlTP13KRLsCJYA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Barium-58b5c23d5f9b586046c8f541.jpg",
	  atomicMass: "137.327(7)",
	  electronicConfiguration: "[Xe] 6s2",
	  electronegativity: 0.89,
	  atomicRadius: 198,
	  oxidationStates: 2,
	  standardState: "solid",
	  meltingPoint: 1000,
	  boilingPoint: 2143,
	  density: 3.51,
	  groupBlock: "alkaline earth metal",
	  yearDiscovered: 1808,
	  block: "s",
	  applications: "medical imaging",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Lanthanum-2.jpg/330px-Lanthanum-2.jpg",
	  name: "Lanthanum",
	  arrangement:"https://www.thoughtco.com/thmb/WtfOUIo9ABPAF8TnS60kbzDq4kU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Lanthanum-58b6018f3df78cdcd83ced65.jpg",
	  atomicMass: "138.90547(7)",
	  electronicConfiguration: "[Xe] 5d1 6s2",
	  electronegativity: 1.1,
	  atomicRadius: 169,
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1193,
	  boilingPoint: 3737,
	  density: 6.146,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1839,
	  block: "f",
	  applications: "catalyst",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Cerium2.jpg/330px-Cerium2.jpg",
	  name: "Cerium",
	  arrangement:"https://www.thoughtco.com/thmb/rJ_EQymNFgfEP71ELwBrb-3j9Ho=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Cerium-58b6018a5f9b5860464bf13b.jpg",
	  atomicMass: "140.116(1)",
	  electronicConfiguration: "[Xe] 4f1 5d1 6s2",
	  electronegativity: 1.12,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3 4",
	  standardState: "solid",
	  meltingPoint: 1071,
	  boilingPoint: 3633,
	  density: 6.689,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1803,
	  block: "f",
	  applications: "polishing",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Praseodymium.jpg/330px-Praseodymium.jpg",
	  name: "Praseodymium",
	  arrangement:"https://www.thoughtco.com/thmb/Y-_3EtaESUCjWcSU-TQO8XeoqLw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Praseodymium-58b601843df78cdcd83ce759.jpg",
	  atomicMass: "140.90765(2)",
	  electronicConfiguration: "[Xe] 4f3 6s2",
	  electronegativity: 1.13,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3 4",
	  standardState: "solid",
	  meltingPoint: 1204,
	  boilingPoint: 3563,
	  density: 6.64,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1885,
	  block: "f",
	  applications: "colouring glass",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Neodymium2.jpg/330px-Neodymium2.jpg",
	  name: "Neodymium",
	  arrangement:"https://www.thoughtco.com/thmb/LEKAQvaknBLoLhrr2g8ksVVOB-A=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Neodymium-58b6017f5f9b5860464bec6a.jpg",
	  atomicMass: "144.242(3)",
	  electronicConfiguration: "[Xe] 4f4 6s2",
	  electronegativity: 1.14,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1294,
	  boilingPoint: 3373,
	  density: 7.01,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1885,
	  block: "f",
	  applications: "lasers",
	},
	{
	  appearance: "/images/radioactive.png",
	  name: "Promethium",
	  arrangement:"https://www.thoughtco.com/thmb/WSRFea9YOBroh2egY6WkEw456K8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Promethium-58b6017a3df78cdcd83ce164.jpg",
	  atomicMass: [145],
	  electronicConfiguration: "[Xe] 4f5 6s2",
	  electronegativity: 1.13,
	  atomicRadius: "unknown",
	  oxidationStates: 3,
	  standardState: "solid",
	  meltingPoint: 1373,
	  boilingPoint: 3273,
	  density: 7.264,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1947,
	  block: "f",
	  applications: "luminous paint",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Samarium-2.jpg/330px-Samarium-2.jpg",
	  name: "Samarium",
	  arrangement:"https://www.thoughtco.com/thmb/_A-qehPOk6XFER0i53k_0AV3fnk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Samarium-58b601743df78cdcd83cddbe.jpg",
	  atomicMass: "150.36(2)",
	  electronicConfiguration: "[Xe] 4f6 6s2",
	  electronegativity: 1.17,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1345,
	  boilingPoint: 2076,
	  density: 7.353,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1853,
	  block: "f",
	  applications: "nuclear reactor",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Europium.jpg/330px-Europium.jpg",
	  name: "Europium",
	  arrangement:"https://www.thoughtco.com/thmb/ltxMArVHbORFHQRgq-u-tWYBjlw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Europium-58b6016e3df78cdcd83cdb23.jpg",
	  atomicMass: "151.964(1)",
	  electronicConfiguration: "[Xe] 4f7 6s2",
	  electronegativity: 1.2,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1095,
	  boilingPoint: 1800,
	  density: 5.244,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1901,
	  block: "f",
	  applications: "fluorescents",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Gadolinium-4.jpg/330px-Gadolinium-4.jpg",
	  name: "Gadolinium",
	  arrangement:"https://www.thoughtco.com/thmb/KFWUH2mr-AfrDaNp85-a7880qcI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Gadolinium-58b6016a5f9b5860464bdfdc.jpg",
	  atomicMass: "157.25(3)",
	  electronicConfiguration: "[Xe] 4f7 5d1 6s2",
	  electronegativity: 1.2,
	  atomicRadius: "unknown",
	  oxidationStates: "1 2 3",
	  standardState: "solid",
	  meltingPoint: 1586,
	  boilingPoint: 3523,
	  density: 7.901,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1880,
	  block: "f",
	  applications: "neutron capture",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Terbium-2.jpg/330px-Terbium-2.jpg",
	  name: "Terbium",
	  arrangement:"https://www.thoughtco.com/thmb/ALA2Tj7E-khSIPIVJiZucAJaiVA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Terbium-58b601653df78cdcd83cd594.jpg",
	  atomicMass: "158.92535(2)",
	  electronicConfiguration: "[Xe] 4f9 6s2",
	  electronegativity: 1.2,
	  atomicRadius: "unknown",
	  oxidationStates: "1 3 4",
	  standardState: "solid",
	  meltingPoint: 1629,
	  boilingPoint: 3503,
	  density: 8.219,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1843,
	  block: "f",
	  applications: "fuel cell",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Dy_chips.jpg/330px-Dy_chips.jpg",
	  name: "Dysprosium",
	  arrangement:"https://www.thoughtco.com/thmb/sYeWBf93VP8nNZKnAXokHTfqbw8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Dysprosium-58b601605f9b5860464bd9df.jpg",
	  atomicMass: "162.500(1)",
	  electronicConfiguration: "[Xe] 4f10 6s2",
	  electronegativity: 1.22,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1685,
	  boilingPoint: 2840,
	  density: 8.551,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1886,
	  block: "f",
	  applications: "nuclear reactor",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Holmium2.jpg/330px-Holmium2.jpg",
	  name: "Holmium",
	  arrangement:"https://www.thoughtco.com/thmb/kfsJDHdJe0SUPa-j4hZzp5kyiR0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Holmium-58b6015b5f9b5860464bd78f.jpg",
	  atomicMass: "164.93032(2)",
	  electronicConfiguration: "[Xe] 4f11 6s2",
	  electronegativity: 1.23,
	  atomicRadius: "unknown",
	  oxidationStates: 3,
	  standardState: "solid",
	  meltingPoint: 1747,
	  boilingPoint: 2973,
	  density: 8.795,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1878,
	  block: "f",
	  applications: "MRI tech",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Erbium-crop.jpg/255px-Erbium-crop.jpg",
	  name: "Erbium",
	  arrangement:"https://www.thoughtco.com/thmb/JrdfHUdk2ECeu8eNmZXZRaKb744=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Erbium-58b601565f9b5860464bd562.jpg",
	  atomicMass: "167.259(3)",
	  electronicConfiguration: "[Xe] 4f12 6s2",
	  electronegativity: 1.24,
	  atomicRadius: "unknown",
	  oxidationStates: 3,
	  standardState: "solid",
	  meltingPoint: 1770,
	  boilingPoint: 3141,
	  density: 9.066,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1842,
	  block: "f",
	  applications: "lasers",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Thulium_sublimed_dendritic_and_1cm3_cube.jpg/330px-Thulium_sublimed_dendritic_and_1cm3_cube.jpg",
	  name: "Thulium",
	  arrangement:"https://www.thoughtco.com/thmb/yLvOfFj9vb_huhdHjJVN_VmED-s=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Thulium-58b601513df78cdcd83ccbd2.jpg",
	  atomicMass: "168.93421(2)",
	  electronicConfiguration: "[Xe] 4f13 6s2",
	  electronegativity: 1.25,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1818,
	  boilingPoint: 2223,
	  density: 9.321,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1879,
	  block: "f",
	  applications: "superconductor",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Ytterbium-3.jpg/330px-Ytterbium-3.jpg",
	  name: "Ytterbium",
	  arrangement:"https://www.thoughtco.com/thmb/V7QcuRg8rjaai0EMQ6PmYNHx3zY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Ytterbium-58b6014c5f9b5860464bcf6d.jpg",
	  atomicMass: "173.054(5)",
	  electronicConfiguration: "[Xe] 4f14 6s2",
	  electronegativity: 1.1,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1092,
	  boilingPoint: 1469,
	  density: 6.57,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1878,
	  block: "f",
	  applications: "stainless steel",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Lutetium_sublimed_dendritic_and_1cm3_cube.jpg/330px-Lutetium_sublimed_dendritic_and_1cm3_cube.jpg",
	  name: "Lutetium",
	  arrangement:"https://www.thoughtco.com/thmb/nloVQCU-IZkSBoNyIkoQRJP3IPM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Lutetium-58b601473df78cdcd83cc606.jpg",
	  atomicMass: "174.9668(1)",
	  electronicConfiguration: "[Xe] 4f14 5d1 6s2",
	  electronegativity: 1.27,
	  atomicRadius: 160,
	  oxidationStates: 3,
	  standardState: "solid",
	  meltingPoint: 1936,
	  boilingPoint: 3675,
	  density: 9.841,
	  groupBlock: "lanthanoid",
	  yearDiscovered: 1907,
	  block: "d",
	  applications: "catalyst",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hf-crystal_bar.jpg/330px-Hf-crystal_bar.jpg",
	  name: "Hafnium",
	  arrangement:"https://www.thoughtco.com/thmb/EVEGdX2o3MyXgV0hu7HqyBHxZAQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Hafnium-58b601425f9b5860464bc918.jpg",
	  atomicMass: "178.49(2)",
	  electronicConfiguration: "[Xe] 4f14 5d2 6s2",
	  electronegativity: 1.3,
	  atomicRadius: 150,
	  oxidationStates: "2 3 4",
	  standardState: "solid",
	  meltingPoint: 2506,
	  boilingPoint: 4876,
	  density: 13.31,
	  groupBlock: "transition metal",
	  yearDiscovered: 1923,
	  block: "d",
	  applications: "superalloy",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Tantalum_single_crystal_and_1cm3_cube.jpg/330px-Tantalum_single_crystal_and_1cm3_cube.jpg",
	  name: "Tantalum",
	  arrangement:"https://www.thoughtco.com/thmb/ooGvxT-c4qFDRtuMnYL1gEsMS4I=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Tantalum-58b6013c3df78cdcd83cc000.jpg",
	  atomicMass: "180.94788(2)",
	  electronicConfiguration: "[Xe] 4f14 5d3 6s2",
	  electronegativity: 1.5,
	  atomicRadius: 138,
	  oxidationStates: "-1 2 3 4 5",
	  standardState: "solid",
	  meltingPoint: 3290,
	  boilingPoint: 5731,
	  density: 16.65,
	  groupBlock: "transition metal",
	  yearDiscovered: 1802,
	  block: "d",
	  applications: "capacitor",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Wolfram_evaporated_crystals_and_1cm3_cube.jpg/330px-Wolfram_evaporated_crystals_and_1cm3_cube.jpg",
	  name: "Tungsten",
	  arrangement:"https://www.thoughtco.com/thmb/qJgK-08lloCAjUtmCn82c-L8QOM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Tungsten-58b601373df78cdcd83cbc93.jpg",
	  atomicMass: "183.84(1)",
	  electronicConfiguration: "[Xe] 4f14 5d4 6s2",
	  electronegativity: 2.36,
	  atomicRadius: 146,
	  oxidationStates: "-2 -1 1 2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 3695,
	  boilingPoint: 5828,
	  density: 19.25,
	  groupBlock: "transition metal",
	  yearDiscovered: 1783,
	  block: "d",
	  applications: "armour-piercing",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Rhenium_single_crystal_bar_and_1cm3_cube.jpg/330px-Rhenium_single_crystal_bar_and_1cm3_cube.jpg",
	  name: "Rhenium",
	  arrangement:"https://www.thoughtco.com/thmb/2PkKpBO1zBDHUYmna4NWJO2whFo=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Rhenium-58b6012b5f9b5860464bbcaa.jpg",
	  atomicMass: "186.207(1)",
	  electronicConfiguration: "[Xe] 4f14 5d5 6s2",
	  electronegativity: 1.9,
	  atomicRadius: 159,
	  oxidationStates: "-3 -1 1 2 3 4 5 6 7",
	  standardState: "solid",
	  meltingPoint: 3459,
	  boilingPoint: 5869,
	  density: 21.02,
	  groupBlock: "transition metal",
	  yearDiscovered: 1925,
	  block: "d",
	  applications: "electricity",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Osmium_crystals.jpg/330px-Osmium_crystals.jpg",
	  name: "Osmium",
	  arrangement:"https://www.thoughtco.com/thmb/7JWlS_sMERKocZu1sFXNu_i1nkQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Osmium-58b601263df78cdcd83cb2c4.jpg",
	  atomicMass: "190.23(3)",
	  electronicConfiguration: "[Xe] 4f14 5d6 6s2",
	  electronegativity: 2.2,
	  atomicRadius: 128,
	  oxidationStates: "-2 -1 1 2 3 4 5 6 7 8",
	  standardState: "solid",
	  meltingPoint: 3306,
	  boilingPoint: 5285,
	  density: 22.61,
	  groupBlock: "transition metal",
	  yearDiscovered: 1803,
	  block: "d",
	  applications: "jewelry",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Iridium-2.jpg/330px-Iridium-2.jpg",
	  name: "Iridium",
	  arrangement:"https://www.thoughtco.com/thmb/mJju_L_vDLv3A3Ie2NVxn06nEjI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Iridium-58b601215f9b5860464bb6e9.jpg",
	  atomicMass: "192.217(3)",
	  electronicConfiguration: "[Xe] 4f14 5d7 6s2",
	  electronegativity: 2.2,
	  atomicRadius: 137,
	  oxidationStates: "-3 -1 1 2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 2739,
	  boilingPoint: 4701,
	  density: 22.65,
	  groupBlock: "transition metal",
	  yearDiscovered: 1803,
	  block: "d",
	  applications: "spark plug",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Platinum_crystals.jpg/330px-Platinum_crystals.jpg",
	  name: "Platinum",
	  arrangement:"https://www.thoughtco.com/thmb/ikc5X-49cig3p7gxJR4VyMC54fA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Platinum-58b6011c5f9b5860464bb4e8.jpg",
	  atomicMass: "195.084(9)",
	  electronicConfiguration: "[Xe] 4f14 5d9 6s1",
	  electronegativity: 2.28,
	  atomicRadius: 128,
	  oxidationStates: "2 4 5 6",
	  standardState: "solid",
	  meltingPoint: 2041,
	  boilingPoint: 4098,
	  density: 21.09,
	  groupBlock: "transition metal",
	  yearDiscovered: "1735",
	  block: "d",
	  applications: "catalyst",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Gold-crystals.jpg/330px-Gold-crystals.jpg",
	  name: "Gold",
	  arrangement:"https://www.thoughtco.com/thmb/PNi2SsV6Vk-yrUNZAkFJuyaJlak=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Gold-58b601163df78cdcd83caa83.jpg",
	  atomicMass: "196.966569(4)",
	  electronicConfiguration: "[Xe] 4f14 5d10 6s1",
	  electronegativity: 2.54,
	  atomicRadius: 144,
	  oxidationStates: "-1 1 2 3 5",
	  standardState: "solid",
	  meltingPoint: 1337,
	  boilingPoint: 3129,
	  density: 19.3,
	  groupBlock: "transition metal",
	  yearDiscovered: "-6000",
	  block: "d",
	  applications: "dentistry",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Pouring_liquid_mercury_bionerd.jpg/330px-Pouring_liquid_mercury_bionerd.jpg",
	  name: "Mercury",
	  arrangement:"https://www.thoughtco.com/thmb/8OATCKbkBCyQbAUgRBO5WgyVWVk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Mercury-58b601125f9b5860464baf39.jpg",
	  atomicMass: "200.59(2)",
	  electronicConfiguration: "[Xe] 4f14 5d10 6s2",
	  electronegativity: 2,
	  atomicRadius: 149,
	  oxidationStates: "1 2 4",
	  standardState: "liquid",
	  meltingPoint: 234,
	  boilingPoint: 630,
	  density: 13.534,
	  groupBlock: "transition metal",
	  yearDiscovered: "-1500",
	  block: "d",
	  applications: "thermometres",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Thallium_pieces_in_ampoule.jpg/330px-Thallium_pieces_in_ampoule.jpg",
	  name: "Thallium",
	  arrangement:"https://www.thoughtco.com/thmb/LGytcdatYHbJtuyMjSljRWCJH1I=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Thallium-58b6010d5f9b5860464bac8b.jpg",
	  atomicMass: "204.3833(2)",
	  electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p1",
	  electronegativity: 2.04,
	  atomicRadius: 148,
	  oxidationStates: "1 3",
	  standardState: "solid",
	  meltingPoint: 577,
	  boilingPoint: 1746,
	  density: 11.85,
	  groupBlock: "metal",
	  yearDiscovered: 1861,
	  block: "p",
	  applications: "poisons",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lead_electrolytic_and_1cm3_cube.jpg/330px-Lead_electrolytic_and_1cm3_cube.jpg",
	  name: "Lead",
	  arrangement:"https://www.thoughtco.com/thmb/_Tml4iChSKMXEtOAVlUDCKBWL2c=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Lead-58b601095f9b5860464ba934.jpg",
	  atomicMass: "207.2(1)",
	  electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p2",
	  electronegativity: 2.33,
	  atomicRadius: 147,
	  oxidationStates: "-4 2 4",
	  standardState: "solid",
	  meltingPoint: 601,
	  boilingPoint: 2022,
	  density: 11.34,
	  groupBlock: "metal",
	  yearDiscovered: "-7000",
	  block: "p",
	  applications: "bullet making",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Bismuth_crystals_and_1cm3_cube.jpg/330px-Bismuth_crystals_and_1cm3_cube.jpg",
	  name: "Bismuth",
	  arrangement:"https://www.thoughtco.com/thmb/xoMLL1gSlmRE8l-iqI69oN01g4w=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Bismuth-58b601035f9b5860464ba6d6.jpg",
	  atomicMass: "208.98040(1)",
	  electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p3",
	  electronegativity: 2.02,
	  atomicRadius: 146,
	  oxidationStates: "-3 3 5",
	  standardState: "solid",
	  meltingPoint: 544,
	  boilingPoint: 1837,
	  density: 9.78,
	  groupBlock: "metal",
	  yearDiscovered: "1000",
	  block: "p",
	  applications: "cosmetics",
	},
	{
	  appearance: "https://upload.wikimedia.org/wikipedia/en/6/66/Polonium.jpg",
	  name: "Polonium",
	  arrangement:"https://www.thoughtco.com/thmb/H_t37uR5I24cWOsOkLaq7siTEUg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Polonium-58b600ff3df78cdcd83c9e23.jpg",
	  atomicMass: [209],
	  electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p4",
	  electronegativity: 2,
	  atomicRadius: "unknown",
	  oxidationStates: "-2 2 4 6",
	  standardState: "solid",
	  meltingPoint: 527,
	  boilingPoint: 1235,
	  density: 9.196,
	  groupBlock: "metalloid",
	  yearDiscovered: 1898,
	  block: "p",
	  applications: "neutron source",
	},
	{
	  appearance:
		"https://engineeredlabs.com/cdn/shop/products/IMG_9411.jpg?v=1635604126",
	  name: "Astatine",
	  arrangement:"https://www.thoughtco.com/thmb/ibRouyDeWtH9tMkKFbhGepJi8Jc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Astatine-58b600fa3df78cdcd83c9bd5.jpg",
	  atomicMass: [210],
	  electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p5",
	  electronegativity: 2.2,
	  atomicRadius: "unknown",
	  oxidationStates: "-1 1 3 5",
	  standardState: "solid",
	  meltingPoint: 575,
	  boilingPoint: 610,
	  density: "unknown",
	  groupBlock: "halogen",
	  yearDiscovered: 1940,
	  block: "p",
	  applications: "not used",
	},
	{
	  appearance: "/images/radioactive.png",
	  name: "Radon",
	  arrangement:"https://www.thoughtco.com/thmb/XYkdSVtzip8_6QZfWYP9-hIHjcw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Radon-58b600f55f9b5860464b9fc0.jpg",
	  atomicMass: [222],
	  electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p6",
	  electronegativity: "unknown",
	  atomicRadius: 145,
	  oxidationStates: 2,
	  standardState: "gas",
	  meltingPoint: 202,
	  boilingPoint: 211,
	  density: 0.00973,
	  groupBlock: "noble gas",
	  yearDiscovered: 1900,
	  block: "p",
	  applications: "not used",
	},
	{
	  appearance:
		"https://www.chemicalbook.com/NewsImg/2019-9-27/2019927140917210.jpg",
	  name: "Francium",
	  arrangement:"https://www.thoughtco.com/thmb/2S2V_9nUjHFifmSrgoiat5HJ2dQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Francium-58b600ef3df78cdcd83c96a2.jpg",
	  atomicMass: [223],
	  electronicConfiguration: "[Rn] 7s1",
	  electronegativity: 0.7,
	  atomicRadius: "unknown",
	  oxidationStates: 1,
	  standardState: "solid",
	  meltingPoint: "300",
	  boilingPoint: "950",
	  density: "2.46",
	  groupBlock: "alkali metal",
	  yearDiscovered: 1939,
	  block: "s",
	  applications: "not used",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Radium226.jpg/330px-Radium226.jpg",
	  name: "Radium",
	  arrangement:"https://www.thoughtco.com/thmb/QonFj_F0HZucca-1CLA10c33Nt4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/radiumelectronshell-58b600ea3df78cdcd83c930f.jpg",
	  atomicMass: [226],
	  electronicConfiguration: "[Rn] 7s2",
	  electronegativity: 0.9,
	  atomicRadius: "unknown",
	  oxidationStates: 2,
	  standardState: "solid",
	  meltingPoint: 973,
	  boilingPoint: 2010,
	  density: 5,
	  groupBlock: "alkaline earth metal",
	  yearDiscovered: 1898,
	  block: "s",
	  applications: "lumo paints",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Actinium_sample_%2831481701837%29.png/330px-Actinium_sample_%2831481701837%29.png",
	  name: "Actinium",
	  arrangement:"https://www.thoughtco.com/thmb/8g3YgHnDLEVaIHwH07d91wHv0O4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Actinium-58b600e45f9b5860464b8b75.jpg",
	  atomicMass: [227],
	  electronicConfiguration: "[Rn] 6d1 7s2",
	  electronegativity: 1.1,
	  atomicRadius: "unknown",
	  oxidationStates: 3,
	  standardState: "solid",
	  meltingPoint: 1323,
	  boilingPoint: 3473,
	  density: 10.07,
	  groupBlock: "actinoid",
	  yearDiscovered: 1899,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Thorium_sample_0.1g.jpg/330px-Thorium_sample_0.1g.jpg",
	  name: "Thorium",
	  arrangement:"https://www.thoughtco.com/thmb/S-m-6L0rfzFSMbCTaFqA7VMCg4g=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Thorium-58b600de5f9b5860464b81a8.jpg",
	  atomicMass: "232.03806(2)",
	  electronicConfiguration: "[Rn] 6d2 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3 4",
	  standardState: "solid",
	  meltingPoint: 2023,
	  boilingPoint: 5093,
	  density: 11.724,
	  groupBlock: "actinoid",
	  yearDiscovered: 1828,
	  block: "f",
	  applications: "nuclear reactor",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Protactinium-233.jpg/330px-Protactinium-233.jpg",
	  name: "Protactinium",
	  arrangement:"https://www.thoughtco.com/thmb/7q4DnQo4PP2QwEFZnNMS-ylf3gw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Protactinium-58b600d93df78cdcd83c75a3.jpg",
	  atomicMass: "231.03588(2)",
	  electronicConfiguration: "[Rn] 5f2 6d1 7s2",
	  electronegativity: 1.5,
	  atomicRadius: "unknown",
	  oxidationStates: "3 4 5",
	  standardState: "solid",
	  meltingPoint: 1845,
	  boilingPoint: 4273,
	  density: 15.37,
	  groupBlock: "actinoid",
	  yearDiscovered: 1913,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/HEUraniumC.jpg/330px-HEUraniumC.jpg",
	  name: "Uranium",
	  arrangement:"https://www.thoughtco.com/thmb/gEU9dJmhF_g_W_zjXi3Nt-oa0M4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Uranium-58b600d43df78cdcd83c6dd1.jpg",
	  atomicMass: "238.02891(3)",
	  electronicConfiguration: "[Rn] 5f3 6d1 7s2",
	  electronegativity: 1.38,
	  atomicRadius: "unknown",
	  oxidationStates: "3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 1408,
	  boilingPoint: 4200,
	  density: 19.05,
	  groupBlock: "actinoid",
	  yearDiscovered: 1789,
	  block: "f",
	  applications: "nuclear weapon",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Np_sphere.jpg/330px-Np_sphere.jpg",
	  name: "Neptunium",
	  arrangement:"https://www.thoughtco.com/thmb/dTiTkravsWvt9VrJmB29ET7pCDQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/neptuniumelectronshell-58b600cd3df78cdcd83c5e29.jpg",
	  atomicMass: [237],
	  electronicConfiguration: "[Rn] 5f4 6d1 7s2",
	  electronegativity: 1.36,
	  atomicRadius: "unknown",
	  oxidationStates: "3 4 5 6 7",
	  standardState: "solid",
	  meltingPoint: 917,
	  boilingPoint: 4273,
	  density: 20.45,
	  groupBlock: "actinoid",
	  yearDiscovered: 1940,
	  block: "f",
	  applications: "nuclear weapon",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/9/98/Plutonium3.jpg",
	  name: "Plutonium",
	  arrangement:"https://www.thoughtco.com/thmb/b5DIY5MJ8UGrz6-j78O_hlv9iE8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Plutonium-58b600bf3df78cdcd83c4408.jpg",
	  atomicMass: [244],
	  electronicConfiguration: "[Rn] 5f6 7s2",
	  electronegativity: 1.28,
	  atomicRadius: "unknown",
	  oxidationStates: "3 4 5 6 7",
	  standardState: "solid",
	  bondingType: "metallic",
	  meltingPoint: 913,
	  boilingPoint: 3503,
	  density: 19.816,
	  groupBlock: "actinoid",
	  yearDiscovered: 1940,
	  block: "f",
	  applications: "nuclear weapon",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Americium_microscope.jpg/330px-Americium_microscope.jpg",
	  name: "Americium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [243],
	  electronicConfiguration: "[Rn] 5f7 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3 4 5 6",
	  standardState: "solid",
	  meltingPoint: 1449,
	  boilingPoint: 2284,
	  density: "unknown",
	  groupBlock: "actinoid",
	  yearDiscovered: 1944,
	  block: "f",
	  applications: "smoke detect",
	},
	{
	  appearance: "https://upload.wikimedia.org/wikipedia/en/6/69/Curium.jpg",
	  name: "Curium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [247],
	  electronicConfiguration: "[Rn] 5f7 6d1 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "3 4",
	  standardState: "solid",
	  meltingPoint: 1618,
	  boilingPoint: 3383,
	  density: 13.51,
	  groupBlock: "actinoid",
	  yearDiscovered: 1944,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/b/b6/Berkelium_metal.jpg",
	  name: "Berkelium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [247],
	  electronicConfiguration: "[Rn] 5f9 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "3 4",
	  standardState: "solid",
	  meltingPoint: 1323,
	  boilingPoint: "unknown",
	  density: 14.78,
	  groupBlock: "actinoid",
	  yearDiscovered: 1949,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/9/93/Californium.jpg",
	  name: "Californium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [251],
	  electronicConfiguration: "[Rn] 5f10 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3 4",
	  standardState: "solid",
	  meltingPoint: 1173,
	  boilingPoint: "unknown",
	  density: 15.1,
	  groupBlock: "actinoid",
	  yearDiscovered: 1950,
	  block: "f",
	  applications: "neutron source",
	},
	{
	  appearance:
		"https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Einsteinium.jpg/195px-Einsteinium.jpg",
	  name: "Einsteinium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [252],
	  electronicConfiguration: "[Rn] 5f11 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "solid",
	  meltingPoint: 1133,
	  boilingPoint: 1269,
	  density: 8.84,
	  groupBlock: "actinoid",
	  yearDiscovered: 1952,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Fermium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [257],
	  electronicConfiguration: "[Rn] 5f12 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "unknown",
	  meltingPoint: 1800,
	  boilingPoint: "unknown",
	  density: 9.7,
	  groupBlock: "actinoid",
	  yearDiscovered: 1952,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Mendelevium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [258],
	  electronicConfiguration: "[Rn] 5f13 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "unknown",
	  meltingPoint: 1100,
	  boilingPoint: "unknown",
	  density: 10.37,
	  groupBlock: "actinoid",
	  yearDiscovered: 1955,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Nobelium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [259],
	  electronicConfiguration: "[Rn] 5f14 7s2",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: "2 3",
	  standardState: "unknown",
	  meltingPoint: 1100,
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "actinoid",
	  yearDiscovered: 1957,
	  block: "f",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Lawrencium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [262],
	  electronicConfiguration: "[Rn] 5f14 7s2 7p1",
	  electronegativity: 1.3,
	  atomicRadius: "unknown",
	  oxidationStates: 3,
	  standardState: "unknown",
	  meltingPoint: 1900,
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1961,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance:
		"https://cdn1.byjus.com/wp-content/uploads/2018/08/Rutherfordium-2.jpg",
	  name: "Rutherfordium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [267],
	  electronicConfiguration: "[Rn] 5f14 6d2 7s2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: 4,
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1969,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Dubnium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [268],
	  electronicConfiguration: "[Rn] 5f14 6d3 7s2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1967,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Seaborgium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [271],
	  electronicConfiguration: "[Rn] 5f14 6d4 7s2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1974,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Bohrium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [272],
	  electronicConfiguration: "[Rn] 5f14 6d5 7s2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1976,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Hassium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [270],
	  electronicConfiguration: "[Rn] 5f14 6d6 7s2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1984,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Meitnerium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [276],
	  electronicConfiguration: "[Rn] 5f14 6d7 7s2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1982,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Darmstadtium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [281],
	  electronicConfiguration: "[Rn] 5f14 6d9 7s1",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1994,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Roentgenium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [280],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s1",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1994,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Copernicium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [285],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "transition metal",
	  yearDiscovered: 1996,
	  block: "d",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Nihonium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [284],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p1",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "post-transition metal",
	  yearDiscovered: 2003,
	  block: "p",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Flerovium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [289],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p2",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "post-transition metal",
	  yearDiscovered: 1998,
	  block: "p",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Moscovium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [288],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p3",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "post-transition metal",
	  yearDiscovered: 2003,
	  block: "p",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Livermorium",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [293],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p4",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "post-transition metal",
	  yearDiscovered: 2000,
	  block: "p",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Tennessine",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [294],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p5",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "post-transition metal",
	  yearDiscovered: 2010,
	  block: "p",
	  applications: "not used",
	},
	{
	  appearance: "/images/radio.jpg",
	  name: "Oganesson",
	  arrangement:"/images/radio.jpg",
	  atomicMass: [294],
	  electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p6",
	  electronegativity: "unknown",
	  atomicRadius: "unknown",
	  oxidationStates: "unknown",
	  standardState: "unknown",
	  meltingPoint: "unknown",
	  boilingPoint: "unknown",
	  density: "unknown",
	  groupBlock: "noble gas",
	  yearDiscovered: 2002,
	  block: "p",
	  applications: "not used",
	},
  ];
let elements = document.querySelectorAll(".elem");
let info_div = document.querySelector(".info_div");
for(let i = 0; i < elements.length; i++){
	let element = elements[i];
	let element_info = info_elements[i];
	element.addEventListener("click", function(){
		info_show(element_info);
	});
};
function info_show(element_info){
	info_div.style.display = "grid";
	info_div.style.gridTemplateColumns = "repeat(2, 1fr)";
	info_div.style.gridTemplateRows = "repeat(2, 1fr)";
	info_div.style.zIndex = 100;
	document.querySelector(".IM1").src = `${element_info.appearance}`
	document.querySelector(".IM2").src = `${element_info.arrangement}`
	document.querySelector(".NM").innerHTML = `name: ${element_info.name}`;
	document.querySelector(".AM").innerHTML = `atomic mass:${element_info.atomicMass} g/mol`;
	document.querySelector(".CF").innerHTML = `configuration:${element_info.electronicConfiguration}`;
	document.querySelector(".EN").innerHTML = `electronegativity${element_info.electronegativity}`;
	document.querySelector(".OS").innerHTML = `oxidation states:${element_info.oxidationStates}`;
	document.querySelector(".DS").innerHTML = `density:${element_info.density} g/cm3`;
	document.querySelector(".SS").innerHTML = `standard state:${element_info.standardState}`;
	document.querySelector(".MP").innerHTML = `melting point:${element_info.meltingPoint}K`;
	document.querySelector(".BP").innerHTML = `boiling point:${element_info.boilingPoint}K`;
	document.querySelector(".CL").innerHTML = `class of elem:${element_info.groupBlock}`;
	document.querySelector(".YD").innerHTML = `year discovered:${element_info.yearDiscovered}`;
	document.querySelector(".AP").innerHTML = `applications:${element_info.applications}`;
}
let btn = document.querySelector("#button");
btn.addEventListener("click", function(){
	info_div.style.display = "none";
});